name: 🚀

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ['main']

env: ${{ secrets }}

jobs:
  only-changed:
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.diff.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find projects which have changed
        uses: ./.github/actions/diff
        id: diff
        with:
          only-deployed: true

  build-and-deploy:
    needs: only-changed

    # should have at least one project to run (cannot have empty matrix)
    if: fromJSON(needs.only-changed.outputs.projects)[0] != null

    strategy:
      matrix:
        project: ${{ fromJSON(needs.resolve.outputs.projects) }}
      fail-fast: false

    uses: ./.github/workflows/deploy.yml
    with:
      project: ${{ matrix.project }}

    secrets: inherit
